moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - torso_controller
    - head_cam_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - L_arm_j1
      - L_arm_j2
      - L_arm_j3
      - L_arm_j4
      - L_arm_j5
      - L_arm_j6
      - L_arm_j7

  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R_arm_j1
      - R_arm_j2
      - R_arm_j3
      - R_arm_j4
      - R_arm_j5
      - R_arm_j6
      - R_arm_j7

  torso_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - torso_j1
      - torso_j2
      - torso_j3

  head_cam_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - head_j1
      - head_j2
      - head_j3
